# Project information
site_name: Sensel Morph Documentation
site_description: 'Documentation for Sensel Inc'
site_author: 'Peter Nyboer'
site_url: 'https://sensel.github.io/morph-docs/'
site_favicon: 'img/favicon.png'

# Repository
repo_name: 'sensel/morph-docs'
repo_url: 'https://github.com/sensel/morph-docs'

theme:
  name: material
  custom_dir: overrides
  logo: 'img/morph_white.svg'
  logoalt: 'img/sensel-logo-blue.svg'
  logo_home: 'img/sensel-logo-white.svg'

# Copyright
copyright: 'Copyright &copy; 2017-2021 sensel'

nav:
    - Home: index.md
    - Morph: morph.md
    - Software Setups: morph_software.md
    - Soundpack Setups: morph_soundpacks.md
    - SenselApp: app.md
    - Overlay Designer: designer.md
    - API primer: api.md
    - API advanced: api_adv.md
    - API with Arduino: api_arduino.md
    - API calls: sensel_h.html
    - API force calls: sensel_decompress_h.html

extra_css:
  - 'senselcss/sensel.css'
  - 'senselcss/docs.css'
  - 'senselcss/MyFontsWebfontsKit.css'
extra:
  generator: false
  social:
    - icon: fontawesome/regular/building
      link: https://morph.sensel.com
      name: Sensel Website
      label: Sensel Website
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/senselinc
      name: Sensel on Twitter
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/senselinc
      name: Sensel on Facebook
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/senselinc
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/senselinc
      name: Sensel on YouTube
